"""add_custom_fields_and_automation

Revision ID: 4297889670de
Revises: baf515839420
Create Date: 2026-07-25 03:33:09.217487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4297889670de'
down_revision: Union[str, Sequence[str], None] = 'baf515839420'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_field_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('field_type', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('placeholder', sa.String(length=500), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('default_value', sa.String(length=500), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('validation_rules', sa.JSON(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('custom_field_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custom_field_definitions_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom_field_definitions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom_field_definitions_organization_id'), ['organization_id'], unique=False)

    op.create_table('scheduled_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('recipients', sa.JSON(), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scheduled_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduled_reports_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_reports_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hired_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('custom_fields', sa.JSON(), nullable=True))

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_fields', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('custom_fields')

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_column('custom_fields')
        batch_op.drop_column('hired_date')

    with op.batch_alter_table('scheduled_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_reports_organization_id'))
        batch_op.drop_index(batch_op.f('ix_scheduled_reports_id'))

    op.drop_table('scheduled_reports')
    with op.batch_alter_table('custom_field_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custom_field_definitions_organization_id'))
        batch_op.drop_index(batch_op.f('ix_custom_field_definitions_id'))
        batch_op.drop_index(batch_op.f('ix_custom_field_definitions_entity_type'))

    op.drop_table('custom_field_definitions')
    # ### end Alembic commands ###
